+name: Deploy to Firebase Hosting on PR
on:
  push:
    branches: [main]
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Change directory, Install and Build Dependencies
        working-directory: ./frontend
        run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_CERTIFY_14 }}"
          projectId: certify-14
